[package]
name = "polynomial"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dashmap = "6.1.0"
polyfill-rs = "0.2.3"
serde_json = "1.0.148"
smol_str = "0.3.4"
thiserror = "2.0.17"
chrono = "0.4"
tokio = { version = "1.49.0", features = ["full"] }
